title: Will's Home Page
email: wts012201@gmail.com

# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: william-sigala-89061424b

show_excerpts: true
excerpt_ separator: <!--more-->

# Build settings
# theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

